# Generated by Django 3.2.15 on 2023-04-12 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_info', '0006_settlementaccountmodel'),
        ('good_info', '0004_auto_20230329_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('invoices_date', models.DateTimeField(verbose_name='单据日期')),
                ('number_code', models.CharField(max_length=28, verbose_name='单据编号,不让用户填写')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='优惠率,最多精确到小数点后两位')),
                ('discount_money', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='优惠金额(付款优惠),最多精确到小数点后两位')),
                ('remark', models.CharField(blank=True, max_length=512, null=True, verbose_name='备注')),
                ('last_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13, verbose_name='优惠后总金额,最多精确到小数点后两位')),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='收取定金,最多精确到小数点后两位')),
                ('number_count', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='销售数量,最多精确到小数点后两位')),
                ('status', models.CharField(default='0', max_length=1, verbose_name='状态,0:未审核,1:已审核,2:部分发货,3:全部发货,4:完成销售,5:已收定金')),
                ('operator_user_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='销售人员的真实姓名')),
                ('check_user_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='审核人员的真实姓名')),
                ('customer_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='客户名称')),
                ('attachment_list', models.CharField(blank=True, max_length=20, null=True, verbose_name='附件的id列表，字段的值为: 1,2,3,4')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_info.settlementaccountmodel', verbose_name='结算账户，审核之后不能改')),
                ('check_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审核人员，不能修改')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_info.customermodel', verbose_name='客户，审核之后不能改')),
                ('operator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_sale_list', to=settings.AUTH_USER_MODEL, verbose_name='销售操作人员，不能修改')),
            ],
            options={
                'verbose_name': '销售表',
                'verbose_name_plural': '销售表',
                'db_table': 't_sales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=20, verbose_name='货品名称')),
                ('number_code', models.CharField(blank=True, max_length=28, null=True, verbose_name='货品的编号或者批号')),
                ('specification', models.CharField(blank=True, max_length=50, null=True, verbose_name='货品规格')),
                ('model_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='型号')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='颜色')),
                ('units_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='单位名字')),
                ('remark', models.CharField(blank=True, max_length=512, null=True, verbose_name='备注')),
                ('sales_count', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='销售数量,最多精确到小数点后两位')),
                ('sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='销售单价,最多精确到小数点后两位')),
                ('sales_money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='销售金额,最多精确到小数点后两位')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='good_info.goodsmodel', verbose_name='货品')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_list', to='sale_info.salemodel', verbose_name='销售单')),
                ('units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='good_info.unitsmodel')),
            ],
            options={
                'verbose_name': '销售订单的项目表',
                'verbose_name_plural': '销售订单的项目表',
                'db_table': 't_sales_items',
                'ordering': ['id'],
            },
        ),
    ]
