# Generated by Django 3.2.15 on 2023-04-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemodel',
            name='invoices_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='单据日期'),
        ),
    ]
