# Generated by Django 3.2.15 on 2023-03-28 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=100, verbose_name='类别名称')),
                ('number_code', models.CharField(max_length=28, unique=True, verbose_name='编号')),
                ('remark', models.CharField(blank=True, max_length=512, null=True, verbose_name='备注')),
                ('order_number', models.IntegerField(default=100, verbose_name='排序号码')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='good_info.goodscategorymodel')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
                'db_table': 't_category',
                'ordering': ['order_number', 'id'],
            },
        ),
    ]
