# Generated by Django 3.2.15 on 2023-03-22 15:59

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='排序数字')),
                ('url', models.CharField(blank=True, max_length=256, null=True, verbose_name='菜单网址')),
                ('name', models.CharField(max_length=256, verbose_name='菜单名字')),
                ('delete_flag', models.CharField(default='0', max_length=1, verbose_name='删除标志')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='erp_system.menumodel')),
            ],
            options={
                'verbose_name': '菜单名称',
                'verbose_name_plural': '菜单名称',
                'db_table': 't_menu',
            },
        ),
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='权限名')),
                ('is_menu', models.BooleanField(default=True, verbose_name='是否为菜单')),
                ('method', models.CharField(blank=True, choices=[('POST', '增'), ('GET', '查'), ('PUT', '改'), ('PATCH', '局部改'), ('DELETE', '删')], max_length=16, null=True, verbose_name='请求方法')),
                ('path', models.CharField(blank=True, max_length=128, null=True, verbose_name='请求路径')),
                ('desc', models.CharField(blank=True, max_length=512, null=True, verbose_name='权限描述')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='erp_system.menumodel')),
            ],
            options={
                'verbose_name': '权限列表',
                'verbose_name_plural': '权限列表',
                'db_table': 't_permissions',
            },
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='角色名')),
                ('permission', models.ManyToManyField(blank=True, db_table='t_role_permission', null=True, to='erp_system.PermissionModel')),
            ],
            options={
                'verbose_name': '角色名称',
                'verbose_name_plural': '角色名称',
                'db_table': 't_role',
            },
        ),
        migrations.CreateModel(
            name='DeptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='部门名称')),
                ('address', models.CharField(blank=True, max_length=16, null=True, verbose_name='部门地址')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='erp_system.deptmodel', verbose_name='父部门')),
            ],
            options={
                'verbose_name': '部门列表',
                'verbose_name_plural': '部门列表',
                'db_table': 't_dept',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话号码')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='erp_system.deptmodel', verbose_name='部门')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('roles', models.ManyToManyField(blank=True, db_table='t_user_roles', null=True, to='erp_system.RoleModel')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户列表',
                'verbose_name_plural': '用户列表',
                'db_table': 't_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
