# Generated by Django 3.2.15 on 2023-03-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='permissions',
            field=models.ManyToManyField(blank=True, db_table='t_user_permissions', null=True, to='erp_system.PermissionModel'),
        ),
    ]
