# Generated by Django 3.2.15 on 2023-03-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0002_suppliermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermodel',
            name='delete_flag',
            field=models.CharField(default='0', max_length=1, verbose_name='启用or禁用'),
        ),
    ]
