# Generated by Django 3.2.15 on 2023-03-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0005_warehousemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='仓库名称')),
                ('number_code', models.CharField(max_length=28, unique=True, verbose_name='编号')),
                ('remark', models.CharField(blank=True, max_length=512, null=True, verbose_name='备注')),
                ('init_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='初期金额')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='余额')),
                ('order_number', models.IntegerField(default=100, verbose_name='排序号码')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'db_table': 't_settlement_account',
                'ordering': ['order_number', 'id'],
            },
        ),
    ]
