# Generated by Django 3.2.15 on 2023-04-06 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasestoragemodel',
            name='check_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='check_instorage', to=settings.AUTH_USER_MODEL, verbose_name='审核人员，不能修改'),
        ),
        migrations.AlterField(
            model_name='purchasestoragemodel',
            name='operator_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_in_list', related_query_name='operator_instorage', to=settings.AUTH_USER_MODEL, verbose_name='入库操作人员，不能修改'),
        ),
    ]
