# Generated by Django 3.2.15 on 2023-04-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_info', '0001_initial'),
        ('warehouse_info', '0002_auto_20230406_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasestoragemodel',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_storage', to='purchase_info.purchasemodel', verbose_name='采购订单，审核之后不能改'),
        ),
    ]
