# Generated by Django 3.2.15 on 2023-04-07 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_info', '0001_initial'),
        ('warehouse_info', '0002_auto_20230406_2008'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_info', '0006_settlementaccountmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('pay_date', models.DateTimeField(verbose_name='付款日期')),
                ('number_code', models.CharField(max_length=28, verbose_name='单据编号,不让用户填写')),
                ('pay_money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='付款金额最多精确到小数点后两位')),
                ('remark', models.CharField(blank=True, max_length=512, null=True, verbose_name='备注')),
                ('currency', models.CharField(choices=[('CNY', '人民币'), ('USD', '美元'), ('EUR', '欧元'), ('JPY', '日元'), ('HKD', '港币')], default='CNY', max_length=20, null=True, verbose_name='货币种类')),
                ('pay_category', models.CharField(choices=[('1', '采购定金'), ('2', '采购货款'), ('3', '欠款还款'), ('4', '其他付款')], default='1', max_length=2, null=True, verbose_name='付款类型')),
                ('status', models.CharField(default='0', max_length=1, verbose_name='状态,0:未审核,1:已审核')),
                ('operator_user_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='财务人员的真实姓名')),
                ('check_user_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='审核人员的真实姓名')),
                ('supplier_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='供应商名称')),
                ('attachment_list', models.CharField(blank=True, max_length=20, null=True, verbose_name='附件的id列表，字段的值为: 1,2,3,4')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_info.settlementaccountmodel', verbose_name='结算账户，审核之后不能改')),
                ('check_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审核人员，不能修改')),
                ('operator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_pay_list', to=settings.AUTH_USER_MODEL, verbose_name='财务操作人员，不能修改')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_info.purchasemodel', verbose_name='采购订单，审核之后不能改')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_info.suppliermodel', verbose_name='供应商，审核之后不能改')),
            ],
            options={
                'verbose_name': '付款单表',
                'verbose_name_plural': '付款单表',
                'db_table': 't_payment',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('storage_code', models.CharField(max_length=28, verbose_name='采购入库单编号,不让用户填写')),
                ('should_money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应该 付款金额，最多精确到小数点后两位')),
                ('this_money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='本次 付款金额，最多精确到小数点后两位')),
                ('remark', models.CharField(blank=True, max_length=512, null=True, verbose_name='备注')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_info.paymentmodel', verbose_name='付款单，不能改')),
                ('purchase_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse_info.purchasestoragemodel', verbose_name='采购入库单')),
            ],
            options={
                'verbose_name': '付款单中的 付款项目表',
                'verbose_name_plural': '付款单中的 付款项目表',
                'db_table': 't_payment_item',
                'ordering': ['id'],
            },
        ),
    ]
