# Generated by Django 3.2.15 on 2023-04-07 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_info', '0002_alter_paymentmodel_pay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentitemmodel',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_list', to='financial_info.paymentmodel', verbose_name='付款单，不能改'),
        ),
    ]
