# Generated by Django 3.2.15 on 2023-04-07 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_info', '0001_initial'),
        ('financial_info', '0003_alter_paymentitemmodel_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='purchase_info.purchasemodel', verbose_name='采购订单，审核之后不能改'),
        ),
    ]
