# Generated by Django 3.2.15 on 2023-04-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_info', '0002_auto_20230406_2008'),
        ('financial_info', '0004_alter_paymentmodel_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentitemmodel',
            name='purchase_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_item', to='warehouse_info.purchasestoragemodel', verbose_name='采购入库单'),
        ),
    ]
