# Generated by Django 3.2.15 on 2023-04-07 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0006_settlementaccountmodel'),
        ('financial_info', '0005_alter_paymentitemmodel_purchase_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='basic_info.settlementaccountmodel', verbose_name='结算账户，审核之后不能改'),
        ),
    ]
